# Generated by Django 4.0.3 on 2022-03-15 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=120, unique=True, verbose_name='Язык')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Список языков',
            },
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='начинается с @', max_length=1000, verbose_name='Имя пользователя(username)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Владелец профиля')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили в telegram',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='UserDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_dicts', to='bot_admin.languages', verbose_name='Язык словаря')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dictionaries', to='bot_admin.telegramprofile', verbose_name='Владелец словаря')),
            ],
            options={
                'verbose_name': 'Словарь',
                'verbose_name_plural': 'Список словарей',
            },
        ),
        migrations.CreateModel(
            name='WordsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120, verbose_name='Слово')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dict_values', to='bot_admin.userdictionary', verbose_name='Словарь владелец')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'История словаря',
            },
        ),
    ]
