# Generated by Django 4.0.3 on 2022-03-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0002_userdictionary_bind_tg_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdictionary',
            name='bind_tg_user',
        ),
    ]
