# Generated by Django 4.0.3 on 2022-03-15 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot_admin', '0003_remove_userdictionary_bind_tg_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordshistory',
            name='dictionary',
        ),
        migrations.AddField(
            model_name='wordshistory',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='language_words', to='bot_admin.languages', verbose_name='Язык словаря'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordshistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to=settings.AUTH_USER_MODEL, verbose_name='Владелец словаря'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserDictionary',
        ),
    ]
