# Generated by Django 4.0.3 on 2022-03-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0004_remove_wordshistory_dictionary_wordshistory_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordshistory',
            options={'verbose_name': 'Слово', 'verbose_name_plural': 'История перевода слов'},
        ),
        migrations.AddField(
            model_name='wordshistory',
            name='value',
            field=models.CharField(default='a', max_length=120, verbose_name='Перевод'),
            preserve_default=False,
        ),
    ]
