# Generated by Django 4.0.3 on 2022-03-15 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot_admin', '0005_alter_wordshistory_options_wordshistory_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordshistory',
            options={'ordering': ['-pk'], 'verbose_name': 'Слово', 'verbose_name_plural': 'История перевода слов'},
        ),
        migrations.AddField(
            model_name='wordshistory',
            name='to_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='language_words_2', to='bot_admin.languages', verbose_name='На язык'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wordshistory',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_words', to='bot_admin.languages', verbose_name='С языка'),
        ),
        migrations.AlterField(
            model_name='wordshistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to=settings.AUTH_USER_MODEL, verbose_name='Владелец истории'),
        ),
    ]
