# Generated by Django 4.0.3 on 2022-03-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0006_alter_wordshistory_options_wordshistory_to_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='code_for_translator',
            field=models.CharField(default='RU', max_length=20, verbose_name='Сокращенный код языка'),
            preserve_default=False,
        ),
    ]
