# Generated by Django 4.0.3 on 2022-03-16 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot_admin', '0007_languages_code_for_translator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dictionaries', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Словарь',
                'verbose_name_plural': 'Список созданных словарей',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='DictionaryBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_words', to='bot_admin.dictionary', verbose_name='Словарь')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_dictionaries', to='bot_admin.wordshistory', verbose_name='Слова')),
            ],
            options={
                'verbose_name': 'Заполненный словарь',
                'verbose_name_plural': 'Заполненные словари',
            },
        ),
    ]
