# Generated by Django 4.0.3 on 2022-03-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0008_dictionary_dictionarybooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionarybooks',
            name='dictionary',
        ),
        migrations.RemoveField(
            model_name='dictionarybooks',
            name='word',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wordshistory',
            name='language',
        ),
        migrations.RemoveField(
            model_name='wordshistory',
            name='to_language',
        ),
        migrations.RemoveField(
            model_name='wordshistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dictionary',
        ),
        migrations.DeleteModel(
            name='DictionaryBooks',
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.DeleteModel(
            name='TelegramProfile',
        ),
        migrations.DeleteModel(
            name='WordsHistory',
        ),
    ]
