# Generated by Django 4.0.3 on 2022-03-17 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dictionaries', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Словарь',
                'verbose_name_plural': 'Список созданных словарей',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=120, unique=True, verbose_name='Язык')),
                ('code_for_translator', models.CharField(max_length=20, verbose_name='Сокращенный код языка')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Список языков',
            },
        ),
        migrations.CreateModel(
            name='WordsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120, verbose_name='Слово')),
                ('value', models.CharField(max_length=120, verbose_name='Перевод')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_words', to='translator.languages', verbose_name='С языка')),
                ('to_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_words_2', to='translator.languages', verbose_name='На язык')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to=settings.AUTH_USER_MODEL, verbose_name='Владелец истории')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'История перевода слов',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='DictionaryWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_words', to='translator.dictionary', verbose_name='Словарь')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_dictionaries', to='translator.wordshistory', verbose_name='Слова')),
            ],
            options={
                'verbose_name': 'Заполненный словарь',
                'verbose_name_plural': 'Заполненные словари',
            },
        ),
    ]
