# Generated by Django 4.0.3 on 2022-03-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DictionaryBooks',
            new_name='DictionaryWords',
        ),
    ]
