# Generated by Django 4.0.3 on 2022-03-18 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_ID', models.PositiveIntegerField(verbose_name='ID пользователя')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Владелец профиля')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили в telegram',
                'ordering': ['tg_user_ID'],
            },
        ),
    ]
